variable "resource_group_name" {}
variable "resource_group_location" {}
variable "virtual_network_name" {}
variable "address_space" {}
variable "frontend_nsg_name" {}
variable "backend_nsg_name" {}
variable "frontend_subnet_name" {}
variable "backend_subnet_name" {}
variable "frontend_address_prefixes" {}
variable "backend_address_prefixes" {}
variable "lb_pip_name" {}
variable "backend_pip_name" {}
variable "bastion_subnet_name" {}
variable "bastion_address_prefixes" {}
variable "bastion_name" {}
variable "bastion_location" {}
variable "bastion_pip_name" {}
variable "frontend_vm_name" {}
variable "frontend_nic_name" {}
variable "frontend_vm_size" {}
variable "backend_vm_name" {}
variable "backend_nic_name" {}
variable "backend_vm_size" {}
variable "vm_username" {}
variable "vm_password" {}
variable "kv_name" {}
variable "lb_name" {}
variable "backendpool_name" {}
variable "ip_configuration_name" {}
variable "kv_secret_name" {}
variable "kv_secret_value" {}
variable "vm_username_secret_name" {}
variable "vm_username_secret_value" {}
variable "vm_password_secret_name" {}
variable "vm_password_secret_value" {}
variable "storage_account_name" {}
variable "container_name" {}
variable "container_access_type" {}
variable "sqlserver_username_secret_name" {}
variable "sqlserver_username_secret_value" {}
variable "sqlserver_password_secret_name" {}
variable "sqlserver_password_secret_value" {}
variable "mssqlserver_name" {}
variable "mssqlserver_location" {}
variable "mssql_username_secret_name" {}
variable "mssql_password_secret_name" {}
variable "database_name" {}
